pybo/views/answer_view.py
from flask import Blueprint, request, url_for, redirect, g, flash, render_template

from pybo.models import Question, Answer

from datetime import datetime

from pybo import db

from ..forms import AnswerForm
from pybo.views.auth import login_required

bp=Blueprint('answer', __name__, url_prefix="/answer")

@bp.route('/create/<int:question_id>', methods=['POST'])
@login_required
def create(question_id):
    form=AnswerForm()
    question=Question.query.get_or_404(question_id)
    if form.validate_on_submit():
        content=request.form['content']
        answer=Answer(content=content, create_date=datetime.now(), user=g.user)
        question.answer_set.append(answer)
        db.session.add(answer)
        db.session.commit()
    return redirect(url_for('question.detail', id=question_id))

@bp.route('/modify/<int:answer_id>', methods=['POST', 'GET'])
@login_required
def modify(answer_id):
    answer=Answer.query.get(answer_id)
    form=AnswerForm()
    if g.user != answer.user:
        flash('permisson error')
        return redirect(url_for('question.detail', id=answer.question_id))
    if request.method == 'POST':
        if form.validate_on_submit():
            form.populate_obj(answer)
            answer.modify_date=datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', id=answer.question_id))
    else:
        form=AnswerForm(obj=answer)
    return render_template('answer/form.html', form=form)

@bp.route('/delete/<int:answer_id>')
def delete(answer_id):
    answer=Answer.query.get(answer_id)
    if answer.user != g.user:
        flash('no permission')
    else:
        db.session.delete(answer)
        db.session.commit()
    return redirect(url_for('question.detail', id=answer.question_id))

pybo/views/comment_view.py
from flask import Blueprint, url_for, request, render_template, g, redirect, flash
from datetime import datetime

from pybo.views.auth import login_required
from pybo import db
from pybo.forms import CommentForm
from pybo.models import Comment, Question, Answer


bp=Blueprint('comment', __name__, url_prefix='/comment')


@bp.route('/create/question/<int:question_id>', methods=('GET', 'POST'))
@login_required
def create_question(question_id):
    form = CommentForm()
    question = Question.query.get_or_404(question_id)
    if request.method == 'POST' and form.validate_on_submit():
        comment=Comment(user=g.user, content = form.content.data, create_date = datetime.now(), question=question)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('question.detail', id=question_id))
    return render_template('comment/comment_form.html', form= form)

@bp.route('/modify/question/<int:comment_id>', methods=('GET', 'POST'))
@login_required
def modify_question(comment_id):
    comment=Comment.query.get_or_404(comment_id)

    if g.user != comment.user:
        flash('permission error')
        return redirect(url_for('question.detail', id=comment.answer.id))
    if request.method =='POST':
        form=CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            comment.modify_date=datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', id=comment.question.id))
    else:
        form=CommentForm(obj=comment)
    return render_template('comment/comment_form.html', form=form)

# @bp.route('/delete/answer/<int:comment_id>')
@bp.route('/delete/comment/<int:comment_id>')
@login_required
def delete_question(comment_id):
    comment=Comment.query.get_or_404(comment_id)
    question_id=comment.question.id
    if g.user != comment.user:
        flash('no permission')
        return redirect(url_for('question.detail', id=question_id))
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('question.detail', id=question_id))


@bp.route('/create/answer/<int:answer_id>', methods=('GET', 'POST'))
@login_required
def create_answer(answer_id):
    form = CommentForm()
    answer = Answer.query.get_or_404(answer_id)
    if request.method == 'POST' and form.validate_on_submit():
        comment = Comment(user=g.user, content=form.content.data, create_date=datetime.now(), answer=answer)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('question.detail', id=answer.question.id))
    return render_template('comment/comment_form.html', form=form)

@bp.route('/modify/answer/<int:comment_id>', methods=('GET', 'POST'))
@login_required
def modify_answer(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if g.user != comment.user:
        flash('no permission')
        return redirect(url_for('question.detail', id=comment.answer.id))
    if request.method == 'POST':
        form = CommentForm()
        if form.validate_on_submit():
            form.populate_obj(comment)
            comment.modify_date = datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', id=comment.answer.question.id))
    else:
        form = CommentForm(obj=comment)
    return render_template('comment/comment_form.html', form=form)


@bp.route('/delete/answer/<int:comment_id>')
@login_required
def delete_answer(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    question_id = comment.answer.question.id
    if g.user != comment.user:
        flash('no permission')
        return redirect(url_for('question.detail', id=question_id))
    db.session.delete(comment)
    db.session.commit()
    return redirect(url_for('question.detail', id=question_id))

pybo/views/question_view.py
from flask import Blueprint, render_template, request, redirect, url_for, g, flash
from pybo.models import Question, Answer, User
from sqlalchemy import func

from ..forms import QuestionForm, AnswerForm

from datetime import datetime

from pybo import db
from pybo.views.auth import login_required

bp=Blueprint('question', __name__, url_prefix='/question')

@bp.route('/list')
def _list():
    # pagination
    page = request.args.get('page', type=int, default=1)
    kw=request.args.get('kw', type=str, default='')
    so=request.args.get('so', type=str, default='recent')
    #order
    if so=='popular':
        sub_query=db.session.query(Answer.question_id, func.count('*').label('num_answer'))\
        .group_by(Answer.question_id).subquery()
        question_list=Question.query.outerjoin(sub_query, Question.id == sub_query.c.question_id)\
        .order_by(sub_query.c.num_answer.desc(), Question.create_date.desc())
    else:
        question_list=Question.query.order_by(Question.create_date.desc())


    if kw:
        search='%%{}%%'.format(kw)
        print('dddd'+search)
        sub_query=db.session.query(Answer.question_id, Answer.content, User.username).join(User, Answer.user_id == User.id).subquery()
        question_list=question_list.join(User).outerjoin(sub_query, sub_query.c.question_id == Question.id)\
        .filter(Question.subject.ilike(search) |
                Question.content.ilike(search) |
                User.username.ilike(search) |
                sub_query.c.content.ilike(search) |
                sub_query.c.username.ilike(search) ).distinct()


    question_list=question_list.paginate(page, per_page=10)
    return render_template('question/question.html', question_list=question_list, page=page, kw=kw, so=so)

@bp.route('/detail/<int:id>')
def detail(id):
    form=AnswerForm()
    question=Question.query.get_or_404(id)
    return render_template('question/detail.html', question=question, form=form)

@bp.route('/create', methods=['POST', 'GET'])
@login_required
def create():
    form=QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        question=Question(subject = form.subject.data, content=form.content.data, create_date=datetime.now(), user=g.user )
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('question/create.html', form=form)

@bp.route('/modify/<int:question_id>', methods=['GET', 'POST'])
def modify(question_id):
    question=Question.query.get_or_404(question_id)
    if question.user != g.user:
        flash('not permission')
        return redirect(url_for('question.detail', id=question_id))
    if request.method == 'POST':
        form=QuestionForm()
        if form.validate_on_submit():
            form.populate_obj(question)
            question.modify_date=datetime.now()
            db.session.commit()
            return redirect(url_for('question.detail', id=question_id))
    else:
        form=QuestionForm(obj=question)
    return render_template('question/create.html', form=form)

@bp.route('/delete/<int:question_id>')
def delete(question_id):
    question=Question.query.get(question_id)
    if question.user != g.user:
        flash('no permiosson')
        return redirect(url_for('question.detail', id=question_id))
    db.session.delete(question)
    db.session.commit()
    return redirect(url_for('question._list'))

pybo/views/vote_view.py
from flask import Blueprint, flash, g, redirect, url_for

from pybo import db
from pybo.models import Question, Answer

from pybo.views.auth import login_required

bp=Blueprint('vote', __name__, url_prefix='/vote')

@bp.route('/vote/question/<int:question_id>/')
@login_required
def question(question_id):
    _question=Question.query.get_or_404(question_id)
    if g.user==_question.user:
        flash("you can't vote your question")
    else:
        _question.voter.append(g.user)
        db.session.commit()
    return redirect(url_for('question.detail', id=_question.id))

@bp.route('/answer/vote/<int:answer_id>')
@login_required
def answer(answer_id):
    _answer=Answer.query.get_or_404(answer_id)
    if g.user == _answer.user:
        flash('you can\'t vote your answer')
    else:
        _answer.voter.append(g.user)
        db.session.commit()
    return redirect('{}#answer_{}'.format(url_for('question.detail', id=_answer.question.id), _answer.id))

pybo/templates/question/create.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">Create Question</h5>
        <form method="post" class="post-form my-3">
            {{form.csrf_token }}
            {% for field, errors in form.errors.items() %}
                <div class="alert alert-danger" role="alert">
                    <strong>{{form[field].label}} </strong> {{', '.join(errors)}}
                </div>
            {% endfor %}

             <div class="form-group">
                <label for="subject">Subject</label>
                <input type="text" class="form-control" name="subject" id="subject" value="{{form.subject.data or '' }}" >
            </div>
            <div class="form-group">
                <label for="content">Content</label>
                <textarea class="form-control" name="content" id="content" rows="5"> {{form.content.data or ''}} </textarea>
            </div>

        <button class="btn btn-primary" type=""submit>Submit</button>
    </form>
</div>


{% endblock %}

pybo/templates/question/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    {% for field, errors in form.errors.items() %}
         <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ', '.join(errors) }}
        </div>
    {% endfor %}

    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}

    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- vote part -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ question.voter|length }}</div>
            <a href="#" data-uri="{{ url_for('vote.question', question_id=question.id) }}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">Vote</a>
        </div>
        <div class="col-11"> <!-- question part -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ question.content|markdown }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="badge badge-light p-2">
                            {{ question.create_date|date_time }}
                            |||
                            {% if question.modify_date %}
                            {{ question.modify_date|date_time }}
                            {% endif %}
                        </div>
                    </div>
                    {% if question.user == g.user %}
                    <div class="my-3">
                        <a href="{{ url_for('question.modify', question_id=question.id) }}"
                           class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="#" data-uri="{{ url_for('question.delete', question_id=question.id) }}"
                           class="delete btn btn-sm btn-outline-danger">Delete</a>
                    </div>
                    {% endif %}

                    {% if question.comment_set|length > 0 %}
                    <div class="mt-3">
                    {% for comment in question.comment_set %}
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.user.username }}, {{ comment.create_date|date_time }}
                                {% if comment.modify_date %}
                                (Edit:{{ comment.modify_date|date_time }})
                                {% endif %}
                            </span>
                            {% if g.user == comment.user %}
                            <a href="{{ url_for('comment.modify_question', comment_id=comment.id) }}" class="small">Edit</a>,
                            <a href="#" class="small delete"
                               data-uri="{{ url_for('comment.delete_question', comment_id=comment.id) }}">Delete</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{{ url_for('comment.create_question', question_id=question.id) }}"
                           class="small"><small>Add Comment ..</small></a>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <h5 class="border-bottom my-3 py-2">{{ question.answer_set|length }} answers.</h5>
    {% for answer in question.answer_set %}
    <a name="answer_{{answer.id}}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- vote part -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ answer.voter|length }}</div>
            <a href="#" data-uri="{{ url_for('vote.answer', answer_id=answer.id) }}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">Vote</a>
        </div>
        <div class="col-11">  <!-- question part -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
                    <div class="d-flex justify-content-end">
                        <div class="mb-2">{{ answer.user.username }}</div>
                        <div class="badge badge-light p-2">
                            {% if answer.modify_date %}
                            {{ answer.modify_date|date_time }}

                            \\\\
                            {{ answer.create_date|date_time }}
                            {% endif %}
                        </div>
                    </div>

                    {% if answer.user == g.user %}
                    <div class="my-3">
                        <a href="{{ url_for('answer.modify', answer_id=answer.id) }}"
                           class="btn btn-sm btn-outline-secondary">Edit</a>
                        <a href="#" data-uri="{{ url_for('answer.delete', answer_id=answer.id) }}"
                           class="delete btn btn-sm btn-outline-secondary">Delete</a>

                    </div>

                    {% endif %}

                    {% if answer.comment_set|length > 0 %}
                    <div class="mt-3">
                    {% for comment in answer.comment_set %}
                        <div class="comment py-2 text-muted">
                            <span style="white-space: pre-line;">{{ comment.content }}</span>
                            <span>
                                - {{ comment.user.username }}, {{ comment.create_date|date_time }}
                                {% if comment.modify_date %}
                                (Edit:{{ comment.modify_date|date_time }})
                                {% endif %}
                            </span>
                            {% if g.user == comment.user %}
                            <a href="{{ url_for('comment.modify_answer', comment_id=comment.id) }}" class="small">Edit</a>,
                            <a href="#" class="small delete"
                               data-uri="{{ url_for('comment.delete_answer', comment_id=comment.id) }}">Delete</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{{ url_for('comment.create_answer', answer_id=answer.id) }}"
                           class="small"><small>Add Comment ..</small></a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{{ url_for('answer.create', question_id=question.id) }}" method="post" class="my-3">
        {{form.csrf_token}}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10" {% if not g.user %} disabled {% endif %} ></textarea>
        </div>
        <input type="submit" value="Submit" class="btn btn-primary">
    </form>
</div>

<script>
    $(document).on('click', '.delete', function(){
        if(confirm('Are you sure?')){
            location.href=$(this).data('uri')
        }
    })
    $(".recommend").on('click', function() {
        if(confirm("Are you sure?")) {
            location.href = $(this).data('uri');
        }
    });
</script>
{% endblock %}

pybo/templates/question/question.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">

<!--    order by items-->

    <div class="row justify-content-end my-3">

        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so=='recent' %}selected{% endif %}>recent</option>
                <option value="recommend" {% if so=='recommend' %}selected{% endif %}>recommend</option>
                <option value="popular" {% if so=='popular' %}selected{% endif %}>popular</option>
            </select>
        </div>


        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw or '' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">Search</button>
            </div>
        </div>

    </div>


    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>No</th>
                <th>Vote count</th>
                <th>Subject</th>
                <th>Created By</th>
                <th>Create date</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %}
            {% for question in question_list.items %}
            <tr>
                <td> {{(question_list.page-1) * question_list.per_page + loop.index}} </td>
                <td>
                    {% if question.voter|length > 0 %}
                    <span class="badge badge-warning px-2 py-1">{{ question.voter|length }}</span>
                    {% endif %}
                </td>
                <td><a href="{{url_for('question.detail', id=question.id)}}"> {{question.subject}}</a>
                    {% if question.answer_set|length > 0 %}
                        {{question.answer_set|length}}
                    {% endif %}
                </td>
                <td>{{question.user.username}}</td>
                <td>{{question.create_date|date_time}}</td>
            </tr>
            {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">No Data</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- pagination -->
    <ul class="pagination justify-content-center">
        <!-- prev -->
        {% if question_list.has_prev %}
        <li class="page-item">
<!--            <a class="page-link" href="?page={{ question_list.prev_num }}">Prev</a>-->
             <a class="page-link" data-page="{{ question_list.prev_num }}" href="#">Prev</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Prev</a>
        </li>
        {% endif %}
        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                <li class="page-item">
<!--                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>-->
                    <a class="page-link" data-page="{{ page_num }}" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
           {% else %}
                <li class="disabled">
                    <a class="page-link" href="#">...</a>
                </li>
           {% endif %}
        {% endfor %}
        <!-- next page -->
        {% if question_list.has_next %}
        <li class="page-item">
<!--            <a class="page-link" href="?page={{ question_list.next_num }}">Next</a>-->
            <a class="page-link" data-page="{{ question_list.next_num }}" href="#">Next</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">Next</a>
        </li>
        {% endif %}
    </ul>
    <!-- pagination end -->

    <a href="{{url_for('question.create')}}" class="btn btn-primary">Create Question</a>
</div>

<form id="searchForm" method="get" action="{{ url_for('question._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">

    <input type="hidden" id="so" name="so" value="{{ so }}">

</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });
    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}